GET http://localhost:4000/

###

POST http://localhost:4000/
Content-Type: application/json

{
    "FirstName":"Sneh",
    "LastName":"Jaiswal",
    "Email":"sneh@gmail.com",
    "phoneNo":7089574490,
    "birth_year":2010
}

###
PUT http://localhost:4000/62c1c804a120d210c96fccd9
Content-Type: application/json

{
    "FirstName":"Sneh",
    "LastName":"Jaiswal",
    "Email":"sneh@gmail.com",
    "phoneNo":7089574490,
    "birth_year":2010
}

###
DELETE http://localhost:4000/62c1c804a120d210c96fccd9

###  search api
GET http://localhost:4000/search/62f1071a000ffca88f544121
